# Generated by Django 5.1 on 2024-08-27 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('service_provider', models.CharField(choices=[('gmail', 'Gmail'), ('yandex', 'Yandex'), ('mail_ru', 'Mail.ru')], max_length=100, verbose_name='Почтовый сервис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=1000, verbose_name='Тема сообщения')),
                ('date_sent', models.DateTimeField(verbose_name='Дата отправки')),
                ('date_received', models.DateTimeField(verbose_name='Дата получения')),
                ('email_body', models.TextField(max_length=380000, verbose_name='Текст сообщения')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.emailaccount', verbose_name='Почтовый аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
